### ISSUE TITLE
encoding issues

### ISSUE THREAD

**Issue by edvinf** [StoXProject/RstoxData#16] opened 2019-11-22 10:03 UTC
When parsing a UTF-8 encoded biotic-file, with UTF-8 marked in xml preamble in an R with default locale set to windows-1252, we get incorrect representation of Scandinavian letters (e.g: ø).

**Comment by iambaim** [comment] 2019-11-27 08:58
This is a duplicate of https://github.com/StoXProject/RstoxData/issues/11. I will close this one and we can continue there.

**Closed by iambaim** 2019-11-27 08:58 UTC
Labels: bug
